apiVersion: v1
kind: Service
metadata:
  name: nginx-hosts-service
  labels:
    app: nginx-hosts-service
spec:
  type: NodePort
  ports:
    - port: 9010
      targetPort: 80
      nodePort: 30901
  selector:
    app: nginx-hosts

