apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-lykops-sfs-0
 labels:
   type: nfs
   app: pv
   version: v1
spec:
 capacity:
   storage: 1Gi
 accessModes:
    - ReadWriteMany
 persistentVolumeReclaimPolicy: Recycle
 nfs:
   path: /data/compose/k8s/nginx/web-0
   server: 10.88.9.34
   readOnly: false

